// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kldcnrnkyurwcbxvnhku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsZGNucm5reXVyd2NieHZuaGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2MDMzNjMsImV4cCI6MjA5NDE3OTM2M30.9eDpibey-fXyBjgUNUNx53Z1_x9CqGlJ5-WiBVw97UU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detect a stale/invalidated session (server-side session_not_found) coming
// back as a 401 from any Edge Function invocation, and force a clean sign-out
// so the app doesn't get stuck on a blank screen.
let handlingStaleSession = false;
async function handleStaleSession() {
  if (handlingStaleSession) return;
  handlingStaleSession = true;
  try {
    await supabase.auth.signOut();
  } catch {
    // ignore
  } finally {
    if (typeof window !== "undefined" && window.location.pathname !== "/login") {
      window.location.replace("/login");
    }
  }
}

const customFetch: typeof fetch = async (input, init) => {
  const res = await fetch(input as any, init);
  try {
    const url = typeof input === "string" ? input : (input as Request).url;
    if (res.status === 401 && url.includes("/functions/v1/")) {
      // Server rejected the token. Try to refresh; if that also fails, the
      // session is truly invalid — sign out and bounce to /login so the user
      // isn't stuck on a broken UI (e.g. staff list showing UUIDs).
      const { data: refreshed, error: refreshErr } =
        await supabase.auth.refreshSession();
      if (refreshErr || !refreshed?.session) {
        void handleStaleSession();
      }
    }
  } catch {
    // ignore
  }
  return res;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: { fetch: customFetch },
});
